name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  TARGET_ARCH: x86_64-unknown-linux-gnu

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install minimal stable
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: |
        cargo build --release --target ${TARGET_ARCH} --bin qdrant
        ls -l
    - name: Archive
      uses: actions/upload-artifact@v3
      with:
        name: qdrant-artifact
        path: ./target/${TARGET_ARCH}/release/qdrant
